rtl_airband.conf.example
rtl_airband.cpp

Updated pull on into unstable.
localtime is now a global config value

Add option to allow localtime vs UTC for output filenames

---

config.cpp
config/reference.conf
output.cpp
rtl_airband.cpp
rtl_airband.h

This PR incorporates the changes in PR #62 and addresses the AGC and squelch issue raised in #61.  
It does two things:
* Enhances channel config kw `squelch` to accept a list of squelch values to be applied to corresponding frequencies in `freqs` (maintains backward compatibility with integer values of `squelch`), and
* keeps separate AGC parameters on a frequency-by-frequency basis.
The result is better auto-squelch performance (because signal levels, which may vary significantly depending on frequency, aren't being aggregated across all frequencies in the scan list) and when that's not enough, each frequency can be assigned a squelch value or left on automatic according to user's needs.
It also refactors the code a bit to keep frequency and label (if any) together with squelch and AGC …

Improve squelch handling in scan mode

---

output.cpp
rtl_airband.cpp

This is a subset of the PR to follow for your convenience in case you decide to accept these changes but don't want the squelch improvements I made (see #61).
This PR does two minor things, one of which is potentially quite important for pi users:
* Add check that executing as root when using the Broadcom GPU; if not root, `rtl_airband` dies (without deallocating FFT memory) because `hello_fft` can't map `/dev/mem`, and there appears to be no way to deallocate that memory except for rebooting.
* Add a pragma to suppress a spurious 'maybe-uninitialized' warning from g++.
Neither are critical, but the first one is a protection for newbies who don't realise that, unlike most RTL-SDR applications, this one must run as root and who, even when they try that, may already have exhausted GPU …

Add check for running as root (also, keep g++ happy)

---

rtl_airband.cpp

When the global variable `syslog_opened_squelch = true;`, writes an event to syslog with the frequency that the squelch opened on.
Figured I'd take a shot at my feature request - #113 - looking for a pull into unstable as it looks like that's where all the development happens.
Sample output from `/var/log/daemon.log`:
`Feb 24 11:48:05 scanner1 rtl_airband[2172]: Squelch opened on 133.475`
`Feb 24 11:48:14 scanner1 rtl_airband[2172]: Squelch opened on 133.475`
`Feb 24 11:48:17 scanner1 rtl_airband[2172]: Squelch opened on 127.550`
`Feb 24 11:48:30 scanner1 rtl_airband[2172]: Squelch opened on 133.100`
`Feb 24 11:48:39 scanner1 rtl_airband[2172]: Squelch opened on 126.500`
`Feb 24 11:48:52 scanner1 rtl_airband[2172]: Squelch opened on 126.500`
`Feb 24 11:49:03 scanner1 rtl_airband[2172]: …

log frequency when squelch opened in scan mode

---

pulse.cpp

pulse_data's `name` was not being used anywhere, but I imagine this is its intended purpose. It defaults to "rtl_airband".

Use the pulseaudio config `name` as context name

---

config.cpp
rtl_airband.cpp
rtl_airband.h

Almost all of my NFM channels use CTCSS tones and the highpass filter didn't do enough to get rid of the hum.  Many of the tones are up at 150Hz - 200Hz and setting the lowpass filtering that high distorts the audio too much.
This adds a simple notch filter class based on the algorithm here: https://www.dsprelated.com/showcode/173.php
Here is an example of configuring with `notch_q` and `notch_gain` being optional.  Let me know if you want the name / structure to change:
```
freq = 155.02500;
modulation = "nfm";
notch = 173.8;
notch_q = 2.4;
notch_gain = 0.9;
```

Add notch filter to suppress CTCSS tones

---

config.cpp
output.cpp
rtl_airband.h

create new config options for 'file' and 'rawfile':
- include_freq: add the frequency in Hz to the end of the filename
- split_on_transmission: create a file per "transmission" rather than one per hour
Rework struct file_data and file open/close logic to support split_on_transmission

Support splitting file by transmission

---

config.cpp
rtl_airband.cpp
rtl_airband.h

Added a configurable bandwidth filter for NFM signals.  Can be set either for single channel or scan mode.
Filter is implemented as a low-pass after de-rotating then checking the average power vs squelch.
The calculation of the filter coefficients is based entirely on a simplification of what is posted here: https://www-users.cs.york.ac.uk/~fisher/mkfilter/
NOTE: Also change the default FFT size to 1024 when NFM is enabled.

Add bandwidth filter

---

makefile
rtl_airband.cpp

Added a `WITH_PROFILING` option to the makefile that enables and links in Gperftools (can be installed with `apt-get install google-perftools libgoogle-perftools-dev`)
Profiling on a rpi3 using a ~100Mb test file showed large amounts of time spent in loading the FFT array:
```
Total: 3238 samples
573  17.7%  17.7%      573  17.7% fftwf_codelet_t2fv_8_neon ??:0
386  11.9%  29.6%      386  11.9% demodulate RTLSDR-Airband/rtl_airband.cpp:456
377  11.6%  41.3%      377  11.6% demodulate RTLSDR-Airband/rtl_airband.cpp:457
324  10.0%  51.3%      324  10.0% fftwf_codelet_n2fv_32_neon ??:0
176   5.4%  56.7%      176   5.4% demodulate RTLSDR-Airband/rtl_airband.cpp:455
154   4.8%  61.5%      154   4.8% demodulate RTLSDR-Airband/rtl_airband.cpp:454
116   3.6%  65.0%      116   3.6% fftwf_cpy2d ??:0 …
```

Add Profiling

---

input-rtlsdr.cpp
rtl_airband.cpp

Make sure that controller thread returns first so that it does not
attempt to set center frequency on a closed device.
After that, call rtlsdr_close from rtlsdr_stop.  Reference rtl_test
for an example of closing the device.

Close RTLSDR device upon exit

---

config.cpp
output.cpp
rtl_airband.cpp
rtl_airband.h

Call lame_encode_flush_nogap when closing a file of type
O_FILE (MP3 output file).
Call disable_device_outputs upon exit. This should close
any open files and shutdown the Pulse audio cleanly.
Also close LAME encoding context for each channel if it was
started up.

Flush mp3 file output writes and close LAME context upon exit

---

config.cpp
mixer.cpp
output.cpp
rtl_airband.cpp
rtl_airband.h

- add logging and stats for output thread overruns and mixer input/output overruns
- wait for mixer and output threads on shutdown
- write final stats file on shutdown

Logging for output thread and mixer thread overruns

---

mixer.cpp
output.cpp
rtl_airband.cpp
rtl_airband.h

Added configuration flag `multiple_output_threads` (defaulted to `false`) that will create an output thread per device and a separate thread for all mixers (if any).
This is done by moving the mp3 condition and mutex variables from globals to objects of a new class `Signal`, modifying `output_thread()` to operate on select device / mixer ranges, and connecting device/mixer thread(s) to output thread(s).

Add flag to split output into multiple threads

---

makefile

Add build platform 'native' that uses `-march=native` and `-mtune=native` and should work well for both raspberry pi v3 and v4 as well as others.  Here is what it evaluates to on those:
Raspberry PI 3:
```
$ gcc -march=native -mtune=native -Q --help=target | grep 'mtune\|march'
-march=                     		armv8-a+crc+simd
-mtune=                     		cortex-a53
```
Raspberry PI 4:
```
$ gcc -march=native -mtune=native -Q --help=target | grep 'mtune\|march'
-march=                     		armv8-a+crc+simd
-mtune=                     		cortex-a72
```

add 'native' platform makefile

---

config.cpp
input-file.cpp
makefile
output.cpp
rtl_airband.cpp
rtl_airband.h
squelch.cpp
squelch.h

This PR is based on #225 but makes cleanup that causes very minor diff.  For example shifting delay by 2 samples will increase/decrease squelch time and thereby the audio output by that number of samples.
My intent was to merge #225 first followed by this, so if anyone has a problem they could roll back to just after #225 merges to know if it was due to one of these minor changes or due to the refactoring in general.
With that said, it may be easier to review this PR rather than #225 (ie this doesn't have a bunch of TODO comments and throwaway code)

Refactor squelch update

---

config.cpp
input-file.cpp
makefile
output.cpp
rtl_airband.cpp
rtl_airband.h
squelch.cpp
squelch.h

This PR refactors the existing squelch algorithm into a new class in an attempt to decouple from the actual demodulation.
The expectation here is no diff in the demodulated output against current code and I verified that using the AM and NFM recordings that I have.  (NOTE: I need to make a bug fix on the `unstable` branch and pushed that for reference here: https://github.com/charlie-foxtrot/RTLSDR-Airband/tree/refactor_squelch_baseline)
There are several places that caused diff (although insignificant) in my first pass, so I made changes here to eliminate the diff and commented as a TODO.  I'll remove those and clean up in a following PR (because it will cause some diff).
There is a change in scan mode in that each frequency has its own `Squelch` object (and therefore state counters), …

Refactor squelch

---

config.cpp
input-file.cpp
makefile
output.cpp
rtl_airband.cpp
rtl_airband.h
squelch.cpp
squelch.h

Addition on top of #226 that adds a config option to generate debug output files for each squelch object, then the file(s) can then be loaded / plotted.
For example, here is the signal and audio output:
and plotting of the debug data:

Add squelch debug output file

---

output.cpp
rtl_airband.cpp
rtl_airband.h
squelch.cpp
squelch.h

multiple improvements to squelch algorithm:
- using buffer to compare pre and post filter samples due to filter's delay
- track "flap count" and drop squelch threshold when things get "flappy"
- check for power after OPENING delay before going to OPEN
- check for power after CLOSING delay before going to CLOSED
- is_open() returns true through CLOSING incase it goes back to OPEN
- add LOW_POWER_ABORT state with is_open() returning false and no power check after delay
- add / rename stats fields

multiple improvements to squelch algorithm

---

config.cpp
output.cpp
rtl_airband.cpp
rtl_airband.h
squelch.cpp
squelch.h
util.cpp

Built on top of #230 with the addition of:
- Define squelch level as dB over noise
- Allow configuration of both normal and flappy squelch levels (in dB)
- Cache some calculations rather than re-calculating each time
- Change "signal power" to "signal level" - not actually measuring "power"

Squelch db

---

rtl_airband.cpp
squelch.cpp
squelch.h

A raw signal level can cross the squelch threshold, but if a bandwidth filter is configure and removes too much of that signal (ie no signal post-filter), the squelch will remain CLOSED.  This change introduces a new waterfall character `~` to indicate when this is happening.
See image below showing the same recording of a 5 kHz signal playing through two "devices" with an FFT size of 1024 and  both devices having multiple channels at 7.5 kHz spacing.  The first "device" has bandwidth on each channel set at 5 kHz and the second "device" has no bandwidth configured.  Power levels between the two devices are shown as the same.  On the two immediate side channels the "with bandwidth" device has squelch closed and showing the new character while the "without bandwidth" device shows squelch …

new waterfall char for signal outside of bandwidth

---

src/squelch.cpp

Change the noise_floor increase from `0.00000001f` to `0.00000003f`.  It appears that smaller values are optimized out somewhere (I tried disabling `fast-math` and that wasn't it)

 Noise floor doesnt raise

---

src/CMakeLists.txt

Make sure that exported functions (i.e. {device}_input_new()) will land in the dynamic symbol table, regardless of level of optimization.
I experienced missing symbols using GCC (10.3.1) with Buildroot (2022-11-rc2). That build environment doesn't leverage the "historical" implicit exporting enabled on other distros through the following module:
/usr/share/cmake-{cmake-version}/Modules/Platform/Linux-GNU.cmake
---
This is an improved implementation superseding #338

Set ENABLE_EXPORTS property for rtl_airband

---

.github/workflows/build.yml

- add rpi3b worker
- bump total run time
- reorganize workers to get mac that take the longest jobs started sooner

ci workflow changes:

---

.devcontainer/Dockerfile.ubuntu-20.04
.devcontainer/Dockerfile.ubuntu-latest
.github/install_dependencies
.github/workflows/build.yml
.gitignore

- add more time to the CI workflow - mac build back over 35 minutes
- changes to Linux docker container to avoid apt issues with Docker caches

CI build tweaks - `main` failing

---

.github/install_dependencies
.github/workflows/build.yml

`brew install` will cause a `brew upgrade` on any installed package that is out of date, and one of these is failing.
Avoiding calling `brew update` when running as a GitHub Action and assuming the OS image is already up to date "enough" avoids the `brew upgrade` of those already installed packages

Fix Mac CI build failures on `main`

---

.github/install_dependencies

Add environment variables to prevent `brew` from checking or updating already installed packages when running in GitHub Workflow

More mac build failures on `main`

---

CMakeLists.txt
Dockerfile
scripts/find_version

add script to get version string either from git or parent dir name

Detect `RTL_AIRBAND_VERION` when building from a release archive

---

.github/install_dependencies
Dockerfile
src/input-mirisdr.cpp

- add installing libmirisdr-4 to both docker and CI builds
- fix warnings in input-mirisdr.cpp

Fix mirisdr and add to docker builds

---

.devcontainer/Dockerfile
.github/platform_build
.github/workflows/ci_build.yml
.github/workflows/platform_build.yml
scripts/find_version
src/config.cpp
src/output.cpp
src/rtl_airband.cpp
src/rtl_airband.h

This PR fixes issue #410, specifically two issues identified with MP3 outputs:
* Missing initial header in MP3 files.
* Bad headers distributed throughout files.
* Writes the "lametag" initial header just prior to file close.
* Associates `lame_t` instance lifecycle with outputs, instead of channels. Every MP3 output now has its own MP3 encoding context.

Fix MP3 output corruption

---

src/config.cpp
src/rtl_airband.cpp
src/rtl_airband.h

Fixes https://github.com/rtl-airband/RTLSDR-Airband/issues/508
Correctly initializing the lame context requires config parsing to have been completed: only after config parsing is complete is it known if a channel will require stereo output due to a configured mixer with L/R balance.
Also includes:
A little renaming for clarity
Light refactor of duplicated code into func

Delay initialization of lame (mp3) context until after config parsing is complete
